[pytest]
DJANGO_SETTINGS_MODULE = bugapp.settings
python_files = tests.py test_*.py *_tests.py
testpaths = .
markers =
    smoke: Smoke tests (quick sanity checks)
    integration: Integration tests
    unit: Unit tests